local_backend: true
display_url: https://colosmica-web.pages.dev
backend:
  name: github
  repo: mondinellisg-prog/colosmica-web # Confirmá que este sea el nombre exacto
  branch: main

media_folder: "" # Como tenés las fotos en la raíz, lo dejamos vacío
public_folder: ""

collections:
  - name: "paginas"
    label: "Páginas"
    files:
      - name: "home"
        label: "Página Principal"
        file: "index.html"
        fields:
          - {label: "Título de la Web", name: "title", widget: "string"}
          - {label: "Texto", name: "body", widget: "markdown"}
