backend:
  name: github
  repo: mondinellisg-prog/colosmica-web # Tu repo
  branch: main

media_folder: "" 
public_folder: ""

collections:
  - name: "paginas"
    label: "Páginas"
    files:
      - name: "home"
        label: "Página Principal (Index)"
        file: "index.html"
        fields:
          - {label: "Título de la Web", name: "title", widget: "string"}
          - {label: "Descripción Principal", name: "body", widget: "markdown"}
